services:
  ventas-service:
    build:
      context: ../el-almacen-de-peliculas-online-ventas
      dockerfile: Dockerfile
    image: el-almacen-de-peliculas-online-ventas:latest
    container_name: ventas-service
    restart: unless-stopped
    depends_on:
      catalogo-mysql:
        condition: service_healthy
      shared-rabbitmq:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8083
      VENTAS_DATASOURCE_USERNAME: ${VENTAS_DB_USER}
      VENTAS_DATASOURCE_PASSWORD: ${VENTAS_DB_PASS}
    networks:
      - peliculas-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://localhost:8083/actuator/health > /dev/null || curl -fsS http://localhost:8083/carrito > /dev/null",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

networks:
  peliculas-net:
